/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projetomecanica.telas.visao;

import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Dell
 */
public class Logo extends javax.swing.JFrame {

    /**
     * Creates new form TelaTechnocar
     */
    public Logo() {
        initComponents();
    }
    
    public Void ImageIcon () {
    
        ImageIcon imgRenault = new ImageIcon(getClass().getResource("imagens/Renault.png"));
        
         
        ImageIcon imgFiat = new ImageIcon(getClass().getResource("imagens/Fiat.png"));
        
         
        ImageIcon imgChevrolet = new ImageIcon(getClass().getResource("imagens/Chevrolet.png"));
        

        ImageIcon imgFord = new ImageIcon(getClass().getResource("imagens/Ford.png"));
        

        ImageIcon imgHonda = new ImageIcon(getClass().getResource("imagens/Honda.png"));
        

        ImageIcon imgHyundai = new ImageIcon(getClass().getResource("imagens/Hyundai.png"));
        

        ImageIcon imgKia = new ImageIcon(getClass().getResource("imagens/Kia.png"));
        

        ImageIcon imgMitsubish = new ImageIcon(getClass().getResource("imagens/Mitsubish.png"));
        

        ImageIcon imgPeugeot = new ImageIcon(getClass().getResource("imagens/Peugeot.png"));
        

        ImageIcon imgToyota = new ImageIcon(getClass().getResource("imagens/Toyota.png"));
        

        ImageIcon imgVolks = new ImageIcon(getClass().getResource("imagens/Volks.png"));
        

        ImageIcon imgVolvo = new ImageIcon(getClass().getResource("imagens/Volvo.png"));
        
      
        String marca = (String) (jComboBoxMarcas.getSelectedItem());
        
        if (marca.equals("Chevrolet"))jLabelQuadro.setIcon(imgChevrolet);
        if (marca.equals("Fiat"))jLabelQuadro.setIcon(imgFiat);
        if (marca.equals("Ford"))jLabelQuadro.setIcon(imgFord);
        if (marca.equals("Honda"))jLabelQuadro.setIcon(imgHonda);
        if (marca.equals("Hyundai"))jLabelQuadro.setIcon(imgHyundai);
        if (marca.equals("Kia"))jLabelQuadro.setIcon(imgKia);
        if (marca.equals("Mitsubishi"))jLabelQuadro.setIcon(imgMitsubish);
        if (marca.equals("Peugeot"))jLabelQuadro.setIcon(imgPeugeot);;
        if (marca.equals("Renault"))jLabelQuadro.setIcon(imgRenault);
        if (marca.equals("Toyota"))jLabelQuadro.setIcon(imgToyota);;
        if (marca.equals("Volkswagen"))jLabelQuadro.setIcon(imgVolks);;
        if (marca.equals("Volvo")) jLabelQuadro.setIcon(imgVolvo);
        return null;

     }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabelQuadro = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBoxMarcas = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabelQuadro.setBackground(new java.awt.Color(255, 255, 255));
        jLabelQuadro.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelQuadro.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 0));

        jButton1.setText("EXECUTAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jComboBoxMarcas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { " ", "Chevrolet", "Fiat", "Ford", "Honda", "Hyundai", "Kia", "Mitsubishi", "Peugeot", "Renault", "Toyota", "Volkswagen", "Volvo" }));
        jComboBoxMarcas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxMarcasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBoxMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jLabelQuadro, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(647, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelQuadro, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxMarcas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(491, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ImageIcon ();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBoxMarcasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxMarcasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxMarcasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Logo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Logo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Logo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Logo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Logo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxMarcas;
    private javax.swing.JLabel jLabelQuadro;
    private javax.swing.JPanel jPanel3;
    // End of variables declaration//GEN-END:variables
}
